config:

  name: meson64-6.7
  kind: kernel
  type: mainline
  branch: linux-6.7.y
  last-known-good-tag: v6.7.0
  maintainers:
    - { github: rpardini, name: Ricardo Pardini, email: ricardo@pardini.net, AtriOS-forum: rpardini }

  dts-directories: []
  overlay-directories: []
  auto-patch-dt-makefile: []

  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS"
      - "Documentation/devicetree/bindings/arm/amlogic.yaml"
    do-not-commit-regexes:
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$"
