# Series from patches.libreelec/
	patches.libreelec/linux-0002-rockchip-from-list.patch
	patches.libreelec/linux-0011-v4l2-from-list.patch
	patches.libreelec/linux-1000-drm-rockchip.patch
	patches.libreelec/linux-1001-v4l2-rockchip.patch
	patches.libreelec/linux-1002-for-libreelec.patch
	patches.libreelec/linux-2000-v4l2-wip-rkvdec-hevc.patch
	patches.libreelec/linux-2001-v4l2-wip-iep-driver.patch
# Series from patches.atrios/
	patches.atrios/bt-broadcom-serdev-workaround.patch
	patches.atrios/clk-rk322x-composite-mmc-clk.patch
	-patches.atrios/clk-rockchip-max-frac-divider.patch
	patches.atrios/driver-rk322x-audio-codec.patch
	patches.atrios/driver-rk3288-gpiomem.patch
	patches.atrios/driver-tinkerboard-alc4040-codec.patch
	patches.atrios/drm-rk322x-plane-overlay.patch
	patches.atrios/drm-rk322x-yuv-10bit-modes.patch
	patches.atrios/drm-rockchip-hardware-cursor.patch
	patches.atrios/dts-miqi-fan.patch
	patches.atrios/dts-miqi-hevc-rga.patch
	patches.atrios/dts-miqi-mali-gpu.patch
	patches.atrios/dts-miqi-regulator-fix.patch
	patches.atrios/dts-rk322x-iep-node.patch
	patches.atrios/dts-rk322x-pinctrl-nand.patch
	patches.atrios/dts-rk3288-disable-serial-dma.patch
	patches.atrios/dts-rk3288-fix-mmc-aliases.patch
	patches.atrios/dts-rk3288-gpu-500mhz-opp.patch
	patches.atrios/dts-rk3288-pinctrl-spi2.patch
	patches.atrios/dts-rk3288-thermal-rearrange-zones.patch
	patches.atrios/dts-tinkerboard-bt-rtl8723bs.patch
	patches.atrios/dts-tinkerboard-bt-uart-pins.patch
	patches.atrios/dts-tinkerboard-hevc-rga.patch
	patches.atrios/dts-tinkerboard-sdio-wifi.patch
	patches.atrios/dts-tinkerboard-sdmmc-properties.patch
	patches.atrios/dts-tinkerboard-spi-interface.patch
	patches.atrios/dts-veyron-flag-cache-flush.patch
	patches.atrios/general-add-overlay-compilation-support.patch
	patches.atrios/general-add-overlay-configfs.patch
	patches.atrios/general-add-restart-handler-for-act8846.patch
	patches.atrios/general-dwc2-fix-rk3288-reset-on-wake-quirk.patch
	patches.atrios/general-dwc2-fix-wait-peripheral.patch
	patches.atrios/general-dwc2-fix-wait-time.patch
	patches.atrios/general-dwc2-nak-gadget.patch
	patches.atrios/general-fix-reboot-from-kwiboo.patch
	patches.atrios/general-increase-spdif-dma-burst.patch
	patches.atrios/general-linux-export-mm-trace-rss-stats.patch
	patches.atrios/general-pl330-01-fix-periodic-transfers.patch
	patches.atrios/general-pl330-02-add-support-for-interleaved-transfers.patch
	patches.atrios/general-pl330-04-bigger-mcode-buffer.patch
	patches.atrios/general-pl330-05-fix-unbalanced-power-down.patch
	patches.atrios/general-pl330-06-fix-buffer-underruns.patch
	patches.atrios/general-rk322x-gpio-ir-driver.patch
	patches.atrios/general-rockchip-various-fixes.patch
	patches.atrios/ir-keymap-rk322x-box.patch
	patches.atrios/ir-keymap-xt-q8l-v10.patch
	patches.atrios/misc-tinkerboard-spi-interface.patch
	patches.atrios/mmc-tinkerboard-sdmmc-reboot-fix.patch
	patches.atrios/rk322x-dmc-driver-01-sipv2-calls.patch
	patches.atrios/rk322x-dmc-driver-02-sip-constants.patch
	patches.atrios/rk322x-dmc-driver-03-dfi-driver.patch
	patches.atrios/rk322x-dmc-driver-04-driver.patch
	patches.atrios/rk322x-dwc2-no-clock-gating.patch
	patches.atrios/rk322x-usb-reset-props.patch
	patches.atrios/wifi-ath9k-no-bulk-EP3-EP4.patch
	patches.atrios/wifi-brcmfmac-add-bcm43342.patch
	patches.atrios/wifi-brcmfmac-ap6330-firmware.patch
	patches.atrios/wifi-driver-esp8089.patch
	patches.atrios/wifi-driver-ssv6051.patch
