name: "Build AtriOS"

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Board to build"
        required: true
        default: "atristation"
      branch:
        description: "Kernel branch"
        required: true
        default: "current"
      release:
        description: "Userspace release"
        required: true
        default: "noble"
      target:
        description: "Build target (image or kernel)"
        required: true
        default: "image"
      ui:
        description: "UI variant (minimal/server/xfce)"
        required: true
        default: "minimal"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout AtriOS"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: "Build"
        uses: ./
        with:
          atrios_token: ${{ secrets.GITHUB_TOKEN }}
          atrios_board: ${{ inputs.board }}
          atrios_kernel_branch: ${{ inputs.branch }}
          atrios_release: ${{ inputs.release }}
          atrios_target: ${{ inputs.target }}
          atrios_ui: ${{ inputs.ui }}
          atrios_runner_clean: "yes"
